### PR TITLE
implemented basic carousel component

### PR DESCRIPTION
**Pull request by Suraj-Prakash-Singh**
Created a basic carousel component, which uses the ImageBanner existing component.

## Summary:
- Mapped all the images and used a **currentIndex**, which can be changed automatically after sometime or on clicking next/previous buttons.
- Opacity of the **ImageBanner** is controlled by the **currentIndex** state variable.
- Dots are also controlled by the **currentIndex** state varaible.
- Visibilty of **next/previous** and **dots** handled through props.
- Implemented a auto scroll in case **next/previous** buttons are hidden, which updates the **currentIndex** using a **setInterval**

### CODE REVIEW

**Comment by CodeRoadSoftwares** [comment]
### Change to be done:

1. Move dots inside the image
2. Move Next and Prev buttons inside the image
3. On mouse hover, carousal should stop changing images by itself. 

### Here is an example:
Carousal

**Comment by CodeRoadSoftwares** [comment]
Moreover, while each image should take full carousal width, they are dividing the width.

https://github.com/CodeRoadSoftwares/tealthy/assets/153097390/346b073f-8dad-4fb5-84ca-5b928bcbe98d

**Comment by CodeRoadSoftwares** [comment]
And adding more images, say 5 instead of 3 makes the image width go more and more smaller. (i.e., all images are distributing the total width of carousal)

**Comment by Suraj-Prakash-Singh** [comment]
### Implemented these changes:
- Images take whole width of the carousel.
- Dots come on top of the current image.
- On hovering the carousel stops scrolling.
- Increased size of next and previous buttons.

**Comment by CodeRoadSoftwares** [comment]
### Great job! 👍 

But I feel the need of adding some animations to the carousal. **When changing slides, it should have a left/right slide effect.**

### Fix
1. On small devices the carousal images doesn't maintain the aspect ratio.

image
**It should keep maintaining the aspect ratio regardless of screen width**

### Features
1. To make the carousal more reusable, it should accept an optional **_interval_** prop to set the scroll speed in seconds(NOT ms). While having some default speed also(say, 3s).
3. Add the functionality of links to carousal images. Some objects in banners may have a link key also:
```javascript
const banners = [
  { src: 'banner1.jpg', alt: 'Banner 1'},
  { src: 'banner2.jpg', alt: 'Banner 2', link:'/appointments' },
  { src: 'banner3.jpg', alt: 'Banner 3' },
];
```
In that case, clicking on the image should lead to that url.

**Comment by CodeRoadSoftwares** [comment]
**The objectives are met.**

But this has disturbed the dimensions of carousal. While it should take the width of container it is wrapped into, it takes some fixed width.

image
IN ABOVE IMAGE THE CAROUSAL SHOULD TAKE THE FULL WIDTH OF THE CONTAINER

You're making it fixed here in src/components/Carousal.jsx (line 38)
image

**MAKE IT FIT THE CONTAINER WIDTH**

**Comment by Suraj-Prakash-Singh** [comment]
Fixed the bug, now the Images will take full width of the container.

**Pull request merged**
